[package]
name = "echo-proto"
version = "0.1.0"
authors = ["Thiago Machado da Silva <thi@unifei.edu.br>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"